#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=10
STOP=15
 
start() {        
        echo Multicon start
        # commands to launch application
        multicon &
}                 
 
stop() {          
        echo stop
        # commands to kill application 
        killall multicon
}
